#!/bin/bash

RESULT=`../modulizer.js --root-path root --library-path lib --import-libraries --import-root --include-kernel -- ext`
node -e "$RESULT require(\"/main.js\")" > actual.out
if ! diff expected.out actual.out
then
	echo "FAIL: Output does not match expected."
else
	echo "PASS"
fi
