#!/bin/bash

OUT=`../modulize --output code.js --root-path root --library-path lib --import-dependencies --include-kernel -- ./root/main.js`
CODE=`cat code.js test.js`
node -e "$CODE" > actual.out
if ! diff expected.out actual.out
then
	echo "FAIL: Output does not match expected."
else
	echo "PASS"
fi
