#!/usr/bin/node
/*

  Copyright (C) 2011 Chad Weider

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.

*/

var fs = require('fs');
var pathutil = require('path');
var Modulizer = require('./modulizer').Modulizer;

var breakForError = function (message) {
  process.stderr.write(message + '\n');
  process.exit(1);
}

var find = require('./utility').find;
var subtractSets = require('./utility').subtractSets;

var args = process.argv.slice(2);
var arg;

var options = {};
options.rootPath = process.cwd();
options.libraryPaths = [];
importPaths = [];
excludePaths = [];
reportPath = undefined;

while (arg = args.shift()) {
  if (arg.slice(0,2) != '--') {
    importPaths.push(args);
    break;
  } else if (arg == '--') {
    importPaths = importPaths.concat(args);
    break;
  }

  switch (arg) {
    case '--library-path':
      arg = args.shift();
      if (!arg || arg == '--') {
        breakForError("Path must be provided for --library-path");
      }
      options.libraryPath = arg;
      break;
    case '--root-path':
      arg = args.shift();
      if (!arg || arg == '--') {
        breakForError("Path must be provided for --root-path");
      }
      options.rootPath = arg;
      break;
    case '--report':
      arg = args.shift();
      if (!arg || arg == '--') {
        breakForError("Path must be provided for --report");
      }
      reportPath = arg;
      break;
    case '--exclude':
      arg = args.shift();
      if (!arg || arg == '--') {
        breakForError("Path must be provided for --exclude");
      }
      var paths = fs.readFileSync(arg, 'utf8')
        .replace(/\n\n+/, '\n')
        .replace(/^\n+/)
        .replace(/\n+$/)
        .split('\n');
      excludePaths = excludePaths.concat(paths);
      break;
    case '--global-key-path':
      arg = args.shift();
      if (!arg || arg == '--') {
        breakForError("Key must be provided for --global-key-path");
      }
      options.globalKeyPath = arg;
      break;
    case '--import-library':
      options.importLibrary = true;
      break;
    case '--import-root':
      options.importRoot = true;
      break;
    case '--import-dependencies':
      options.importDependencies = true;
      break;
    case '--include-kernel':
      options.kernel = true;
      break;
    default:
      breakForError("Unknown option: " + arg);
  }
}
options.import = importPaths;
options.exclude = excludePaths;

var paths = [];
if (options.importRoot && options.rootPath) {
  paths.push(options.rootPath);
}
if (options.importRoot && options.libraryPath) {
  paths.push(options.libraryPath);
}
paths = paths.concat(options.import);


var writeStream = process.stdout;
if (options.kernel) {
  writeStream.write((options.globalKeyPath || "var require") + ' = ', 'utf8');
  writeStream.write(fs.readFileSync(pathutil.join(__dirname, 'kernel.js')));
  writeStream.write(";\n", 'utf8');
}

var writeReport = function (error, paths) {
  if (reportPath) {
    writeStream.write(paths.join('\n') + '\n', 'utf8');
  }
};

var modulizer = new Modulizer(options);
find(paths,
  function (path) {
    return pathutil.extname(path) == '.js'
  }
, function (error, paths) {
    paths = paths || [];
    paths = modulizer.systemToModulePaths(paths);
    paths = subtractSets(paths, options.exclude);
    var package = function (paths) {
      modulizer.package(paths, writeStream, writeReport)
    };
    if (options.importDependencies) {
      modulizer.dependencies(paths, package);
    } else {
      package(paths);
    }
  }
);
