#!/bin/bash

../../modulize dependencies --root-path ../root --library-path ../lib -- ../root/main.js | xargs ../../modulize package --root-path ../root --library-path ../lib --include-kernel -- > /tmp/code.js
cp /tmp/code.js /tmp/compiled.js
echo "require('/main.js', function () {});" >> /tmp/compiled.js
node /tmp/compiled.js > /tmp/actual.out
if ! diff expected.out /tmp/actual.out
then
	echo "FAIL: Output does not match expected."
else
	echo "PASS"
fi
