#!/bin/bash

../../modulize --root-path ../root --library-path ../lib --import-dependencies --include-kernel -- ../root/main.js > /tmp/code.js
cp /tmp/code.js /tmp/compiled.js
echo "require('/main.js', function () {});" >> /tmp/compiled.js
node /tmp/compiled.js > /tmp/actual.out
if ! diff expected.out /tmp/actual.out
then
	echo "FAIL: Output does not match expected."
else
	echo "PASS"
fi
